/**
 * In this file there are 2 const arrays with movies and actors.
 * The allMoviesArray contains all the needed information to display the movie and also a list of actors ids who play in.
 * The actors array contains all the useful information about actors and the movie ids which play in.
 */

const allMoviesArray = {
    0: {
        "id": 1,
        "title": "Wonka",
        "year": 2023,
        "image": "../images/movies/movies/movie" + "0" + ".webp",
        "type": "Adventure",
        "duration": "1h 57m",
        "trailer": "https://www.youtube.com/embed/otNh9bTjXWg?si=PTcFt3bv1QjKf-0i",
        "description": "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
        "actors": [1, 2, 3],
    },
    1: {
        "id": 2,
        "title": "Fist of Fury",
        "year": 1972,
        "image": "../images/movies/movies/movie" + "1" + ".webp",
        "type": "Action",
        "duration": "1h 48m",
        "trailer": "https://www.youtube.com/embed/oO9PVJdgu4M?si=9DowKIL-mbr-PQdl",
        "description": "Returning to Shanghai to marry his fiancée, Chen Zhen (Bruce Lee) a student of renowned martial arts teacher Huo Yuanjia, discovers his sifu has died. During the funeral, members of a local Japanese dojo show up and insult the Chinese students. The bullying continues, with Chen fighting back, but when he discovers the truth - that his teacher was poisoned on the orders of the dojo's master - he sets off on a doomed mission of revenge.",
        "actors": [3, 4, 5],
    },
    2: {
        "id": 3,
        "title": "Scrooge",
        "year": 1970,
        "image": "../images/movies/movies/movie" + "2" + ".webp",
        "type": "Drama",
        "duration": "1h 53m",
        "trailer": "https://www.youtube.com/embed/EDWxqmEBG_s?si=B8Na6gEqCuUtVgkR",
        "description": "A musical retelling of Charles Dickens' classic novel about an old bitter miser taken on a journey of self-redemption, courtesy of several mysterious Christmas apparitions.",
        "actors": [3, 4, 5],
    },
    3: {
        "id": 4,
        "title": "FernGully",
        "year": 1992,
        "image": "../images/movies/movies/movie" + "3" + ".webp",
        "type": "Animation",
        "duration": "1h 20m",
        "trailer": "https://www.youtube.com/embed/Dzqyc95zcxo?si=nLoQx1ZcWd_buLK_",
        "description": "When a sprite named Crysta shrinks a human boy, Zak, down to her size, he vows to help the magical fairy folk stop a greedy logging company from destroying their home: the pristine rainforest known as FernGully. Zak and his new friends fight to defend FernGully from lumberjacks — and the vengeful spirit they accidentally unleash after chopping down a magic tree.",
        "actors": [1, 2],
    },
    4: {
        "id": 5,
        "title": "Poor Things",
        "year": 2023,
        "image": "../images/movies/movies/movie" + "4" + ".webp",
        "type": "Drama",
        "duration": "2h 22m",
        "trailer": "https://www.youtube.com/embed/RlbR5N6veqw?si=aBYfdZblj66zz7Ur",
        "description": "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
        "actors": [1, 2],
    },
    5: {
        "id": 6,
        "title": "Dune",
        "year": 2021,
        "image": "../images/movies/movies/movie" + "5" + ".webp",
        "type": "Drama",
        "duration": "2h 22m",
        "trailer": "https://www.youtube.com/embed/RlbR5N6veqw?si=aBYfdZblj66zz7Ur",
        "description": "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
        "actors": [1, 2, 3],
    },
    6: {
        "id": 7,
        "title": "Shrek",
        "year": 2001,
        "image": "../images/movies/movies/movie" + "6" + ".webp",
        "type": "Drama",
        "duration": "2h 22m",
        "trailer": "https://www.youtube.com/embed/RlbR5N6veqw?si=aBYfdZblj66zz7Ur",
        "description": "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
        "actors": [1, 2],
    },
    7: {
        "id": 8,
        "title": "Interstellar",
        "year": 2014,
        "image": "../images/movies/movies/movie" + "7" + ".webp",
        "type": "Drama",
        "duration": "2h 22m",
        "trailer": "https://www.youtube.com/embed/RlbR5N6veqw?si=aBYfdZblj66zz7Ur",
        "description": "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
        "actors": [1, 2],
    },
    8: {
        "id": 9,
        "title": "Wonka",
        "year": 2023,
        "image": "../images/movies/movies/movie" + "0" + ".webp",
        "type": "Adventure",
        "duration": "1h 57m",
        "trailer": "https://www.youtube.com/embed/otNh9bTjXWg?si=PTcFt3bv1QjKf-0i",
        "description": "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
        "actors": [1, 2],
    },
    9: {
        "id": 10,
        "title": "Fist of Fury",
        "year": 1972,
        "image": "../images/movies/movies/movie" + "1" + ".webp",
        "type": "Action",
        "duration": "1h 48m",
        "trailer": "https://www.youtube.com/embed/oO9PVJdgu4M?si=9DowKIL-mbr-PQdl",
        "description": "Returning to Shanghai to marry his fiancée, Chen Zhen (Bruce Lee) a student of renowned martial arts teacher Huo Yuanjia, discovers his sifu has died. During the funeral, members of a local Japanese dojo show up and insult the Chinese students. The bullying continues, with Chen fighting back, but when he discovers the truth - that his teacher was poisoned on the orders of the dojo's master - he sets off on a doomed mission of revenge.",
        "actors": [3, 4, 5],
    },
    10: {
        "id": 11,
        "title": "Scrooge",
        "year": 1970,
        "image": "../images/movies/movies/movie" + "2" + ".webp",
        "type": "Drama",
        "duration": "1h 53m",
        "trailer": "https://www.youtube.com/embed/EDWxqmEBG_s?si=B8Na6gEqCuUtVgkR",
        "description": "A musical retelling of Charles Dickens' classic novel about an old bitter miser taken on a journey of self-redemption, courtesy of several mysterious Christmas apparitions.",
        "actors": [3, 4, 5],
    },
    11: {
        "id": 12,
        "title": "FernGully",
        "year": 1992,
        "image": "../images/movies/movies/movie" + "3" + ".webp",
        "type": "Animation",
        "duration": "1h 20m",
        "trailer": "https://www.youtube.com/embed/Dzqyc95zcxo?si=nLoQx1ZcWd_buLK_",
        "description": "When a sprite named Crysta shrinks a human boy, Zak, down to her size, he vows to help the magical fairy folk stop a greedy logging company from destroying their home: the pristine rainforest known as FernGully. Zak and his new friends fight to defend FernGully from lumberjacks — and the vengeful spirit they accidentally unleash after chopping down a magic tree.",
        "actors": [1, 2],
    },
    12: {
        "id": 13,
        "title": "Poor Things",
        "year": 2023,
        "image": "../images/movies/movies/movie" + "4" + ".webp",
        "type": "Drama",
        "duration": "2h 22m",
        "trailer": "https://www.youtube.com/embed/RlbR5N6veqw?si=aBYfdZblj66zz7Ur",
        "description": "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
        "actors": [1, 2],
    },
    13: {
        "id": 14,
        "title": "Dune",
        "year": 2021,
        "image": "../images/movies/movies/movie" + "5" + ".webp",
        "type": "Drama",
        "duration": "2h 22m",
        "trailer": "https://www.youtube.com/embed/RlbR5N6veqw?si=aBYfdZblj66zz7Ur",
        "description": "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
        "actors": [1, 2],
    },
    14: {
        "id": 15,
        "title": "Shrek",
        "year": 2001,
        "image": "../images/movies/movies/movie" + "6" + ".webp",
        "type": "Drama",
        "duration": "2h 22m",
        "trailer": "https://www.youtube.com/embed/RlbR5N6veqw?si=aBYfdZblj66zz7Ur",
        "description": "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
        "actors": [1, 2],
    },
    15: {
        "id": 16,
        "title": "Interstellar",
        "year": 2014,
        "image": "../images/movies/movies/movie" + "7" + ".webp",
        "type": "Drama",
        "duration": "2h 22m",
        "trailer": "https://www.youtube.com/embed/RlbR5N6veqw?si=aBYfdZblj66zz7Ur",
        "description": "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
        "actors": [1, 2],
    },
}

const actors = {
    0: {
        'id': 1,
        'image': "../images/movies/actors/actor0.webp",
        'name': "Timothée Chalamet",
        'bio': "Timothée Hal Chalamet (born December 27, 1995) is an American actor. He began his career appearing in the drama series Homeland in 2012. Two years later, hemade his film debut in the comedy-drama Men, Women & Children and appeared in Christopher Nolan's science fiction film Interstellar. He came into attention in Luca Guadagnino's coming-of-age film Call Me by Your Name (2017). Alongside supporting roles in Greta Gerwig's films Lady Bird (2017) and Little Women (2019), he took on starring roles in Beautiful Boy (2018) and Dune (2021).",
        'movies': [1, 2, 6, 7, 3, 5, 4, 9, 10, 15, 16],
    },
    1: {
        'id': 2,
        'image': "../images/movies/actors/actor1.webp",
        'name': "Calah Lane",
        'bio': "Calah Francie Lane (born April 20, 2009) is an American teen actress, singer, and dancer. Her breakthrough was her role as main character Noodle opposite Timothée Chalamet in the Warner Bros. production Wonka (2023), directed by Paul King, in which she was nominated for a 2023 Critics' Choice Award in the category Best Young Actor/Actress.",
        'movies': [1, 2, 6, 7, 3, 5, 4, 9, 10, 15, 16],
    },
    2: {
        'id': 3,
        'image': "../images/movies/actors/actor2.webp",
        'name': "Keegan Key",
        'bio': "Keegan-Michael Key (born March 22, 1971, height 6' 1\" (1,85 m)) is an American actor and comedian best known for starring in the Comedy Central sketch series Key & Peele and for his six seasons as a cast member on MADtv.",
        'movies': [1, 3, 4, 5, 6, 7],
    },
    3: {
        'id': 4,
        'image': "../images/movies/actors/actor3.webp",
        'name': "Bruce Lee",
        'bio': "Bruce Jun Fan Lee (Lee Siu Lung) was born on November 27, 1940 in San Francisco, CA while his parents were on tour with the Chinese Opera. Ultimately raised in Hong Kong, Bruce Lee was a child actor appearing in more than 20 films. At the age of 13, Bruce took up the study of wing chun gung fu under renowned wing chun master, Yip Man.",
        'movies': [1, 2, 3],
    },
    4: {
        'id': 5,
        'image': "../images/movies/actors/actor4.webp",
        'name': "Nora Miao",
        'bio': "Nora Miao is a Chinese actress, most well known for her roles in Bruce Lee's \"Big Boss\", \"Fist of Fury\" and \"Way of the Dragon\".",
        'movies': [1, 2, 3, 4, 5, 6, 7],
    },
    5: {
        'id': 6,
        'image': "../images/movies/actors/actor5.webp",
        'name': "James Tien Chuen",
        'bio': "James Tien-chun (Chinese: 田俊; born 28 May 1942) is a Hong Kong actor from Guangdong, China. He appeared in almost 70 films, primarily in Hong Kong action cinema, including roles in the films of martial arts stars including Bruce Lee, Jackie Chan and Sammo Hung. He often played villains or supporting roles. He retired from the Hong Kong film industry in 1996.",
        'movies': [1, 2, 3, 4, 5, 6, 7],
    },
    6: {
        'id': 1,
        'image': "../images/movies/actors/actor0.webp",
        'name': "Timothée Chalamet",
        'bio': "Timothée Hal Chalamet (born December 27, 1995) is an American actor. He began his career appearing in the drama series Homeland in 2012. Two years later, hemade his film debut in the comedy-drama Men, Women & Children and appeared in Christopher Nolan's science fiction film Interstellar. He came into attention in Luca Guadagnino's coming-of-age film Call Me by Your Name (2017). Alongside supporting roles in Greta Gerwig's films Lady Bird (2017) and Little Women (2019), he took on starring roles in Beautiful Boy (2018) and Dune (2021).",
        'movies': [1, 2, 3, 4, 6, 7],
    },
    7: {
        'id': 2,
        'image': "../images/movies/actors/actor1.webp",
        'name': "Calah Lane",
        'bio': "Calah Francie Lane (born April 20, 2009) is an American teen actress, singer, and dancer. Her breakthrough was her role as main character Noodle opposite Timothée Chalamet in the Warner Bros. production Wonka (2023), directed by Paul King, in which she was nominated for a 2023 Critics' Choice Award in the category Best Young Actor/Actress.",
        'movies': [3, 6, 7],
    },
    8: {
        'id': 3,
        'image': "../images/movies/actors/actor2.webp",
        'name': "Keegan Key",
        'bio': "Keegan-Michael Key (born March 22, 1971, height 6' 1\" (1,85 m)) is an American actor and comedian best known for starring in the Comedy Central sketch series Key & Peele and for his six seasons as a cast member on MADtv.",
        'movies': [1, 2, 3, 4, 6, 7],
    },
    9: {
        'id': 4,
        'image': "../images/movies/actors/actor3.webp",
        'name': "Bruce Lee",
        'bio': "Bruce Jun Fan Lee (Lee Siu Lung) was born on November 27, 1940 in San Francisco, CA while his parents were on tour with the Chinese Opera. Ultimately raised in Hong Kong, Bruce Lee was a child actor appearing in more than 20 films. At the age of 13, Bruce took up the study of wing chun gung fu under renowned wing chun master, Yip Man.",
        'movies': [1, 2, 3, 4, 5, 6, 7],
    },
    10: {
        'id': 5,
        'image': "../images/movies/actors/actor4.webp",
        'name': "Nora Miao",
        'bio': "Nora Miao is a Chinese actress, most well known for her roles in Bruce Lee's \"Big Boss\", \"Fist of Fury\" and \"Way of the Dragon\".",
        'movies': [1, 3, 4, 5, 6, 7],
    },
    11: {
        'id': 6,
        'image': "../images/movies/actors/actor5.webp",
        'name': "James Tien Chuen",
        'bio': "James Tien-chun (Chinese: 田俊; born 28 May 1942) is a Hong Kong actor from Guangdong, China. He appeared in almost 70 films, primarily in Hong Kong action cinema, including roles in the films of martial arts stars including Bruce Lee, Jackie Chan and Sammo Hung. He often played villains or supporting roles. He retired from the Hong Kong film industry in 1996.",
        'movies': [1, 2, 3, 4, 5],
    },
    12: {
        'id': 1,
        'image': "../images/movies/actors/actor2.webp",
        'name': "Keegan Key",
        'bio': "Keegan-Michael Key (born March 22, 1971, height 6' 1\" (1,85 m)) is an American actor and comedian best known for starring in the Comedy Central sketch series Key & Peele and for his six seasons as a cast member on MADtv.",
        'movies': [1, 2, 3, 4, 6, 7],
    },
    13: {
        'id': 5,
        'image': "../images/movies/actors/actor4.webp",
        'name': "Nora Miao",
        'bio': "Nora Miao is a Chinese actress, most well known for her roles in Bruce Lee's \"Big Boss\", \"Fist of Fury\" and \"Way of the Dragon\".",
        'movies': [1, 3, 4, 5, 6, 7],
    },
    14: {
        'id': 6,
        'image': "../images/movies/actors/actor5.webp",
        'name': "James Tien Chuen",
        'bio': "James Tien-chun (Chinese: 田俊; born 28 May 1942) is a Hong Kong actor from Guangdong, China. He appeared in almost 70 films, primarily in Hong Kong action cinema, including roles in the films of martial arts stars including Bruce Lee, Jackie Chan and Sammo Hung. He often played villains or supporting roles. He retired from the Hong Kong film industry in 1996.",
        'movies': [1, 2, 3, 4, 5],
    },
}

export {allMoviesArray, actors};